# Generated by Django 4.1.6 on 2023-02-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='tools_and_tasks.bill'),
        ),
    ]
