# Generated by Django 4.1.6 on 2023-02-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0002_alter_constructionobject_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionobject',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools_and_tasks.constructionobject'),
        ),
    ]
