# Generated by Django 4.1.6 on 2023-02-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0004_bill_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, help_text="Insert client's title", max_length=100, null=True, verbose_name='Title'),
        ),
    ]
