# Generated by Django 4.1.6 on 2023-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0005_rename_name_task_title_rename_name_tool_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Picture'),
        ),
    ]
