# Generated by Django 4.1.6 on 2023-02-15 14:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0007_alter_constructionobject_manager_alter_task_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
