# Generated by Django 4.1.6 on 2023-02-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools_and_tasks', '0009_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('text', models.TextField(help_text='Insert your comment', max_length=2000, verbose_name='Comment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_comments', to='tools_and_tasks.tool', verbose_name='Tool')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
