# Generated by Django 4.1.6 on 2023-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0011_constructionobjectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(help_text='Insert tool title', max_length=100, verbose_name='Tool'),
        ),
    ]
