# Generated by Django 4.1.6 on 2023-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0012_alter_tool_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='inventory_number',
            field=models.CharField(help_text='Insert inventory number', max_length=100, unique=True, verbose_name='Inventory number'),
        ),
    ]
