# Generated by Django 4.1.6 on 2023-02-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0013_alter_tool_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(help_text='Insert number of bill', max_length=10, unique=True, verbose_name='Number of bill'),
        ),
    ]
