# Generated by Django 4.1.6 on 2023-02-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0014_alter_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='tools_and_tasks.task', verbose_name='Task'),
        ),
    ]
