# Generated by Django 4.1.6 on 2023-03-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_tasks', '0018_alter_task_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Number of bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid'), ('c', 'Canceled')], default='u', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='constructionobjectcomment',
            name='construction_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_object_comments', to='tools_and_tasks.constructionobject'),
        ),
        migrations.AlterField(
            model_name='constructionobjectcomment',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('a', 'Assigned'), ('p', 'In progress'), ('f', 'Finished'), ('c', 'Canceled')], default='a', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='inventory_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Inventory number'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('b', 'Broken'), ('r', 'In repair'), ('t', 'Taken')], default='a', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tool'),
        ),
        migrations.AlterField(
            model_name='toolcomment',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
    ]
